### PR TITLE
Script to evaluate a full database of hwpss

### PR DESCRIPTION
**Pull request by keskitalo**

### CODE REVIEW

**Review by jlashner — APPROVED** [review]
Looks good, thanks Reijo!

**Comment by keskitalo** [comment]
@jlashner I don't have write permissions to the repo so this PR was left approved but not merged. Do you want to merge it or shall I just close it? I am cleaning up my open PRs.

**Comment by jlashner** [comment]
I can merge it! Do you know if this is being used anywhere?

**Comment by keskitalo** [comment]
I believe I used it to extract the HWPSS database that now is included in sotodlib. For that reason it makes sense to have it merged.

**Pull request merged**
